### ISSUE TITLE
Error with "self.next" when running xml2csv.py module

### ISSUE THREAD

**Issue by ahlusar1989** [knadh/xmlutils.py#24]
When I enter the command prompt as modelled in the Documentation ----->

(xmlutils.xml2csv
from xmlutils.xml2csv import xml2csv
converter = xml2csv("samples/fruits.xml", "samples/fruits.csv", encoding="utf-8")
converter.convert(tag="item"))

I get the following message. The details of the error are below. Please advise on a solution. 

$ python
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1
600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from xmlutils.xml2csv import xmlcsv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'xmlcsv'
>>> from xmlutils.xml2csv import xml2csv
>>> converter = xml2csv("samples/fruits.xml", "samples/fruits.csv" , encoding =
"utf-8")
>>> coverter.convert(tag = "item")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'coverter' is not defined
>>> converter.convert(tag = "item")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c\Python Folder\xmlutils.py\xmlutils\xml2csv.py",
line 56, in convert
    event, root = self.context.next()
AttributeError: '_IterParseIterator' object has no attribute 'next'
>>> converter.convert(tag = "item")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c\Python Folder\xmlutils.py\xmlutils\xml2csv.py",
line 56, in convert
    # event, root = self.context.next()
AttributeError: '_IterParseIterator' object has no attribute 'next'
>>> converter.convert(tag = "item")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c\Python Folder\xmlutils.py\xmlutils\xml2csv.py",
line 56, in convert
    # event, root = self.context.next()
AttributeError: '_IterParseIterator' object has no attribute 'next'

**Comment by ContratsOuvertsMtlUtilisateur** [comment]
I have the same problem.

Have you found a solution?

**Comment by sdiepend** [comment]
Might have to do that you're running it with python 3.4?

**Comment by ContratsOuvertsMtlUtilisateur** [comment]
Yes, I'm using Python 3.4.

**Comment by knadh** [comment]
The library has only been test with Python 2.7. 3x compatibility hasn't been verified.

**Comment by MorganRamsay** [comment]
Same error in Python 3.6.2, by the way.

**Comment by chatchan92** [comment]
Just change line 57 in xml2csv.py from this: event, root = self.context.next() to this: event, root = self.context.__next__()

**Comment by chatchan92** [comment]
Just change line 57 in xml2csv.py from this: event, root = self.context.next() to this: event, root = `self.context.__next__()`

**Comment by mswipedata** [comment]
event, root = self.context.__next__()
AttributeError: 'IterParseIterator' object has no attribute 'next' is the new error you get after the change
