### ISSUE TITLE
Problem specifying tab delimiter

### ISSUE THREAD

**Issue by mrigess** [knadh/xmlutils.py#34]
Hi,

I tried using 
`--delimiter "\t"`
for specifying TAB as the delimiter but that didnt work. Tried escaping also 
`"\\t" `
but it didn't work. Resulted CSV prints \t as text and TAB character is not created.

**Comment by mrigess** [comment]
Hi,

Realized its console issue, it worked like this:

`--delimiter $'\t'`

**Comment by loretoparisi** [comment]
@mrigess same problem until heading here, thanks!
