### ISSUE TITLE
datapacket XML format

### ISSUE THREAD

**Issue by laclaro** [knadh/xmlutils.py#39]
Hi,

I have an xml-file that looks like this

```
<?xml version="1.0" standalone="yes"?>
<DATAPACKET Version="2.0">
    <METADATA>
        <FIELDS>
            <FIELD attrname="test_attribute" fieldtype="string" WIDTH="6" />
        </FIELDS>
        <PARAMS />
    </METADATA>
    <ROWDATA>
        <ROW test_attribute="value" />
    </ROWDATA>
</DATAPACKET>
```

Can one adjust your code to apply it to such a file?

Best,

Henning

**Comment by knadh** [comment]
The lib doesn't convert attributes to CSV, but xml2json should include the attribute values. About modifying, yes, it should be possible.
