### ISSUE TITLE
Cannot convert XML to CSV

### ISSUE THREAD

**Issue by alihammadbaig** [knadh/xmlutils.py#45]
Tried converting simple XML (below)  but get nothing in the output file. Output file is created though. I am using Python v2.7

```
<?xml version="1.0" encoding="utf-8"?>
<rows>
  <row Id="2" PostId="35314"/> 
</rows>
```
Tried command line tool which didn't work
`xml2csv --input "subset.xml" --output "subset.csv" --tag "row"`

Error 

![image](https://user-images.githubusercontent.com/30281264/45071192-6cf30f00-b118-11e8-9e94-37809f56c317.png)

Tried it through the code which didn't work either
```
from xmlutils.xml2csv import xml2csv
converter = xml2csv("subset.xml", "subset.csv", encoding="utf-8")
converter.convert(tag="row")
```

**Comment by manel00** [comment]
Hi, me too, it doesn't work, creates empty CSV

**Comment by knadh** [comment]
Sorry. This library is no longer maintained I'm afraid.
