### ISSUE TITLE
Push the latest changes to pypi.org

### ISSUE THREAD

**Issue by sanjaymp18** [knadh/xmlutils.py#48]
Hi Kailash, Please Push the latest changes that includes support for python 3.x for xml2csv script, as the package available in pypi.org doesn't handle the attribute error.

Thanks!

**Comment by knadh** [comment]
Done.

**Comment by sanjaymp18** [comment]
Thanks @knadh for your quick response, but the package isn't yet updated, please take a look !
[download version](https://pypi.org/project/xmlutils/#files)

**Comment by knadh** [comment]
Woops. Fixed and uploaded `v1.4.1`. I get confused by `twine`!
